[all]
BOOT_UART=1
BOOT_ORDER=0xf17
HTTP_HOST=bootloader.sabsystem.com
HTTP_PORT=18443
HTTP_PATH=/
HTTP_CACERT_HASH=6163585b380cab5a28af59210f7a17acfc4924fd32bced05a11e7c2815f0d1d9
NET_INSTALL_ENABLED=0
SIGNED_BOOT=0
DISABLE_HDMI=0
